[project]
name = "docspec-to-jinja"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "docspec>=2.2.1",
    "docspec-python>=2.2.1",
    "docstring-parser>=0.16",
    "jinja2>=3.1.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
