[tool.poetry]
name = "maya-stubs"
version = "0.2.0"
description = "Stubs for Maya"
authors = ["Loïc Pinsard <muream@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Muream/maya-stubs"
packages = [
    { include = "maya-stubs" },
]

[tool.poetry.dependencies]
python = "^2.7 || ^3.7"

[tool.poetry.dev-dependencies]
black = "*"
pylint = "*"
mypy = "^0.960"
click = "^8.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
