[project]
name = "maya-stubs"
version = "0.4.2"
description = "Type Annotated Stubs for Autodesk Maya's python APIs"
readme = "README.md"
requires-python = ">=3.7"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[tool.hatch.build.targets.wheel]
packages = ["src/maya-stubs"]
