[tool.poetry]
name = "maya-stubs"
version = "0.2.0"
description = "Stubs for Maya"
authors = ["Loïc Pinsard <muream@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Muream/maya-stubs"
packages = [
    { include = "maya-stubs" },
]

[tool.poetry.dependencies]
python = "^2.7 || ^3.7"

[tool.poetry.dev-dependencies]
black = {version = "*", python = "^3.7"}
pylint = "*"
mypy = {version = "*", python = "^3.7"}
click = {version = "*", python = "^3.7"}
redbaron = "^0.9.2"
tqdm = "^4.64.0"

[tool.pylint.messages_control]
max-line-length = 88
disable = [
    "import-error",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
