[project]
name = "maya-stubgen"
version = "0.1.0"
description = "Generate stubs and documentation for maya's Python APIs"
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "docspec>=2.2.1",
    "docspec-python>=2.2.1",
    "requests>=2.32.3",
    "typing-extensions>=4.12.2",
    "docspec-to-jinja",
    "click>=8.1.7",
    "attrs>=24.2.0",
    "httpx>=0.27.2",
]

[project.scripts]
maya-stubgen = 'maya_stubgen.__main__:main'

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
docspec-to-jinja = { workspace = true }
