from __future__ import annotations

from typing import *

import logging

Unknown = Any

class MayaGuiLogHandler(logging.Handler):
    """A python logging handler that displays error and warning
    records with the appropriate color labels within the Maya GUI
    """
    def __init__(self) -> None: ...
    def emit(self, record: Unknown) -> Any: ...

class StringTable:
    """The StringTable object allows access to the application's string catalog which is used, which is used to support application lookup for localized string resources.  The strings in this table may be over written by localized versions, which will then be picked up by scripts that access these values.

    This class behaves in the same way as a Dictionary object in Python with respect to getting and setting values.
    Note that StringTable objects just provide access to the single application-wide string table.  So, creating a new StringTable object does not create a new string table inside the application, it is just another interface to the existing global table.
    """
    def __delitem__(self, key: Unknown, /) -> Any: ...
    def __getitem__(self, key: Unknown, /) -> Any: ...
    def __init__(self, /, *args: Unknown, **kwargs: Unknown) -> None: ...
    def __len__(self, /) -> Any: ...
    def __new__(cls, /, *args: Unknown, **kwargs: Unknown) -> Any: ...
    def __setitem__(self, key: Unknown, value: Unknown, /) -> Any: ...

def abs_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def all_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def any_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def ascii_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def bin_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def bool_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def breakpoint_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def bytearray_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def bytes_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def callable_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def chr_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def classmethod_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def compile_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def complex_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def delattr_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def dict_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def dir_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def divmod_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def enumerate_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def eval_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def exec_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def executeDeferred(*args: Unknown, **kwargs: Unknown) -> Any: ...
def executeInMainThreadWithResult(*args: Unknown, **kwargs: Unknown) -> Any: ...
def filter_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def float_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def formatGuiException(
    exceptionType: Unknown,
    exceptionObject: Unknown,
    traceBack: Unknown,
    detail: int = 2,
) -> Any: ...
def formatGuiResult(obj: Unknown) -> Any: ...
def format_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def frozenset_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def getPossibleCompletions(input: Unknown) -> Any: ...
def getattr_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def globals_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def guiLogHandler() -> Any: ...
def hasattr_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def hash_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def helpNonVerbose(
    thing: Unknown, title: str = "Python Library Documentation: %s", forceload: int = 0
) -> Any: ...
def help_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def hex_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def id_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def input_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def int_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def isinstance_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def issubclass_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def iter_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def len_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def list_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def loadStringResourcesForFile(
    scriptPath: Unknown, fullModulePath: Unknown, resourceFileName: Unknown
) -> Any: ...
def loadStringResourcesForModule(moduleName: Unknown) -> Any: ...
def locals_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def map_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def max_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def memoryview_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def min_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def next_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def object_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def oct_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def open_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def ord_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def pow_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def print_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def processIdleEvents(*args: Unknown, **kwargs: Unknown) -> Any: ...
def property_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def range_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def repr_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def reversed_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def round_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def set_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def setattr_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def shellLogHandler() -> Any: ...
def slice_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def sorted_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def staticmethod_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def str_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def sum_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def super_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def tuple_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def type_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def vars_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
def zip_over(*args: Unknown, **kwargs: Unknown) -> Any: ...
