from __future__ import annotations

from typing import *

Unknown = Any

class MDGContextGuard:
    """Scoping object to manage changes to the current evaluation context"""
    def _MDGContextGuard__save_state(self, new_current_context: Unknown) -> Any: ...
    def __enter__(self) -> Any: ...
    def __exit__(
        self, object_type: Unknown, value: Unknown, traceback: Unknown
    ) -> Any: ...
    def __init__(self, context: Unknown) -> None: ...
    def context(self) -> Any: ...
    def original_context(self) -> Any: ...
    def restore(self) -> Any: ...
