from __future__ import annotations

from typing import *


Unknown = Any

_T = TypeVar("_T")

Queryable = Union[bool, _T]
Multiuse = Union[_T, List[_T]]
Range = Union[Tuple[_T], Tuple[_T, _T]]
NullableRange = Range[Optional[_T]]

def scriptEditorInfo(*, edit: bool = ..., query: bool = ..., clearHistory: bool = ..., clearHistoryFile: bool = ..., historyFilename: Queryable[str] = ..., input: str = ..., suppressErrors: bool = ..., suppressInfo: bool = ..., suppressResults: bool = ..., suppressStackWindow: bool = ..., suppressWarnings: bool = ..., writeHistory: bool = ...) -> Union[str, bool]:
    """Use this command to directly manipulate and query the contents of the
    Command Window window.
    Args:
        clearHistory (bool?): Clears the read-only text in the upper field of the Command Window.  
                Properties: edit
        clearHistoryFile (bool?): Clear the file defined by the -hf/historyFilename flag, but only  
                if -wh/writeHistory is true. Use this flag to start a new history file,  
                since the default behaviour of the Command Window is to append to  
                the existing file.  
                Properties: edit
        historyFilename (Queryable[str]?): Sets or returns the name of the file that the Command Window will  
                use to echo all of its history to. If this is an empty string when  
                the -wh/writeHistory flag is set to true, then it will automatically be  
                set to the default file.  
                Properties: query, edit
        input (str?): Sets the text in the lower field of the Command Window.  
                Set this value to an empty string to clear the field.  
              
                Note: this flag only affects the Command Window and not the new script editor.  
                To find out how to manipulate the new script editor please refer to the documentation  
                on the cmdScrollFieldExecuter and cmdScrollFieldReporter.  
                Properties: edit
        suppressErrors (bool?): When true, Command Window and Script Editor will not display error messages.  
                Properties: query, edit
        suppressInfo (bool?): When true, Command Window and Script Editor will not display info messages  
                generated by Maya.  
                Properties: query, edit
        suppressResults (bool?): When true, Command Window and Script Editor will not display command results.  
                Properties: query, edit
        suppressStackWindow (bool?): When true and when the stackTrace mechanism is on, this  
                flag will suppress the display of the stack window. If stack  
                trace is enabled then results will be returned to the output  
                window instead of a separate stack window.  
                Properties: query, edit
        suppressWarnings (bool?): When true, Command Window and Script Editor will not display warning messages.  
                Properties: query, edit
        writeHistory (bool?): When true, Command Window will echo all of its  
                history to the file defined by the -hf/historyFilename flag. This  
                flag effectively turns file writing on/off.  
                Properties: query, edit

    Returns:
        str: The name of the Command Window window is returned.

    Example:
    """

